name:                universe-simulator
version:             0.1.0.0
github:              "jordanemedlock/universe_simulator"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jordanemedlock/universe_simulator#readme>

dependencies:
- base >= 4.7
- GLFW-b >=3.3
- OpenGL >=3.0
- bindings-GLFW >=3.3
- JuicyPixels >=3.3
- freetype2 >=0.2
- bytestring >=0.10
- filepath >=1.4
- matrix >=0.3
- linear
- raw-strings-qq
- time 
- vector
- transformers
- lens >=4.18
- directory
- apecs
- template-haskell
- random
- unordered-containers
- text
# - gltf-codec

library:
  source-dirs: engine
  exposed-modules: 
  - Engine
  - Engine.Apecs
  # dependencies:
  # - GLFW-b >=3.3 && <4
  # - OpenGL >=3.0 && <4
  # - bindings-GLFW >=3.3 && <4
  # - JuicyPixels >=3.3 && <4
  # - freetype2 >=0.2 && <0.3

executables:
  blank-window:
    source-dirs: examples/blank-window
    main: Main.hs
    dependencies:
    - universe-simulator
  box:
    source-dirs: examples/box
    main: Main.hs
    dependencies:
    - universe-simulator
  textured-box:
    source-dirs: examples/textured-box
    main: Main.hs
    dependencies:
    - universe-simulator
  earth-sphere:
    source-dirs: examples/earth-sphere
    main: Main.hs
    dependencies:
    - universe-simulator
  # ecs:
  #   source-dirs: examples/ecs
  #   main: Main.hs
  #   dependencies:
  #   - universe-simulator
  # text:
  #   source-dirs: examples/text
  #   main: Main.hs
  #   dependencies:
  #   - universe-simulator
  # hack:
  #   source-dirs: examples/hack
  #   main: Main.hs
  #   dependencies:
  #   - universe-simulator
  # solar-system:
  #   source-dirs: examples/solar-system
  #   main: Main.hs
  #   dependencies:
  #   - universe-simulator
  # model-loading:
  #   source-dirs: examples/model-loading
  #   main: Main.hs
  #   dependencies:
  #   - universe-simulator
  vulkan-starter:
    source-dirs: examples/vulkan-starter
    main: Main.hs
    dependencies:
    - vulkan
    - vulkan-utils
    - pretty-simple >=3.3
    - universe-simulator
    # extra-libraries: moltenVK
    
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -Wunused-binds
- -Wunused-imports
# - -ddump-splices
# tests:


default-extensions:
- QuasiQuotes
- OverloadedStrings
- OverloadedLists
- BlockArguments
- FlexibleInstances
- ScopedTypeVariables
- LambdaCase
- TypeApplications
- TypeFamilies
- MultiParamTypeClasses
- FlexibleContexts
- DuplicateRecordFields